# This file demonstrates all available theme configuration options for Vicinae.
# You don't need to define all of these: only override what you want to customize.
# Undefined colors will be automatically derived from core colors or inherited from base themes.
#
# Check out the full documentation at https://docs.vicinae.com/theming/getting-started

[meta]
name = "Vicinae Dark"
description = "Default Vicinae dark palette"
variant = "dark"                              # "dark" | "light": impacts what icon to show in some circumstances
inherits = "vicinae-dark"
icon = "icons/theme-name.png"                 # Optional: path to theme icon (relative to the theme directory it is placed in if not an absolute path)

[colors.core]
accent = "#2f6fed"
accent_foreground = "#ffffff"
background = "#1a1a1a"
foreground = "#e8e6e1"
secondary_background = "#242424"
border = "#2e2e2e"

[colors.main_window]
border = "#2e2e2e"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "#2e2e2e"

[colors.accents]
blue = "#2f6fed"
green = "#3a9c61"
magenta = "#bc8cff"
orange = "#f0883e"
red = "#b9543b"
yellow = "#bfae78"
cyan = "#18a5b3"
purple = "#bc8cff"

# For now, shortcuts cannot have their own dedicated background
[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#e8e6e1"
danger = "#b9543b"
success = "#3a9c61"
placeholder = "#e8e6e1"
selection = { background = "#2f6fed", foreground = "#ffffff" }

[colors.text.links]
default = "#2f6fed"
visited = "#bc8cff"

[colors.input]
border = "#2e2e2e"
border_focus = "#2f6fed"
border_error = "#b9543b"

[colors.button.primary]
background = "#2e2e2e"
foreground = "#e8e6e1"
hover = { background = "#bb2e2e2e" }
focus = { outline = "colors.core.accent" }

[colors.list.item.selection]
background = "#2e2e2e"
foreground = "#e8e6e1"
secondary_background = "#2e2e2e"
secondary_foreground = "#e8e6e1"

[colors.grid.item]
background = "#242424"
hover = { outline = "#e8e6e1" }
selection = { outline = "#e8e6e1" }

[colors.scrollbars]
background = "#2e2e2e"

[colors.loading]
bar = "#e8e6e1"     # shown right below the search bar when something is loading
spinner = "#e8e6e1" # used by dynamic toasts
