name: "Push to Cachix"
on:
  pull_request:
  push:
    paths:
      - typescript
      - vicinae

jobs:
  push_to_cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with:
        name: vicinae
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build Flake
      run: nix build
    - name: Run Test Shell
      run: nix develop --command echo OK 
