name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: self-hosted

jobs:
  format:
    runs-on: [self-hosted, Linux, X64, prod]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check formatting
        run: make check-format
