name: Check Nix Hashes

on:
  push:
    paths:
      - typescript
      - vicinae
  workflow_dispatch:

jobs:
  check-hashes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: cachix/install-nix-action@v31
      - name: Check nix hashes
        run: |
          nix run --accept-flake-config .#nix-update-script
